name: build and push docker image 
on: 
 push:
   branches:
     - dev-branch 
jobs:
  build:
   runs-on: self-hosted 
   steps:
     - name: checkout apiVersion
       uses: checkout/actions@v2 
     - name: login docker 
       uses: docker-login@v2 
       with:
         username: ${{ secrets.DOCKER_USERNAME}}
         password: ${{secrets.DOCKER_PASSWORD}}
     - name: build with docker 
       run: docker build local-image .
     - name: run the image 
       run: docker run -d -p 3030:80 local-image 
     - name: tag image 
       run: docker tag betrand1997:latest/local-image:latest
     - name: push image 
       run: docker push betrand1997:latest/local-image:latest